### ISSUE TITLE
May we change the title "Doing Agile Well" to "Agile Best Practices" or "Good Agile Practices?"

### ISSUE THREAD

**Issue by aliciacyrus** [GSA/cto-website#124]

**Comment by aliciacyrus** [comment]
Or perhaps "Embracing Agile"

**Comment by jcastle** [comment]
@jfredrickson5 can you change this for me real quick?  Since you are probably in the code today anyway and it's minor.  Thanks!

**Comment by jfredrickson5** [comment]
No problem, will get on it.
