### ISSUE TITLE
Improve flow of the Work With Us page

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#125]
(From 10/14 user feedback session)

As it is, the page jumps straight from "How We Work" to the contact form. There should be some kind of easing from "How We Work" to invite people to get in touch with us via the form.

**Comment by saracope** [comment]
Add a couple sentences here.

**Comment by saracope** [comment]
I added a section to the Work with us page for this. Can be viewed here: https://federalist.18f.gov/preview/GSA/cto-website/issue-125/work-with-us/

Screenshot: 

<img width="923" alt="screen shot 2016-10-19 at 7 50 47 am" src="https://cloud.githubusercontent.com/assets/2197515/19517993/85326830-95d2-11e6-933e-e6bd6749ff33.png">

Please review and comment: @jfredrickson5, @jcastle

**Comment by jfredrickson5** [comment]
Looks good!
