### ISSUE TITLE
Add CTO groups to Roadmap page

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#127]
(From 10/14 user feedback session)

Under the various projects OCTO is working on, consider listing which group is leading the effort. For instance, Digital Service, D2D.

Should evaluate how much CTO internal structure matters to our audience. Is this a possible way to improve transparency around how we work? Will it make it easier for our audience to figure out the right person to contact?

**Comment by jcastle** [comment]
Already had #113.  Going to check with Navin.
