### ISSUE TITLE
Consider using Waffle to track sprints

### ISSUE THREAD

**Issue by jcastle** [GSA/cto-website#13]
@jfredrickson5, @saracope and I are using Waffle to track work through sprints.  This feeds off of issues but allows for movement of work through Kanban as opposed to labels.

**Comment by jfredrickson5** [comment]
Where's the waffle board? I'd like to see it in action and get ideas.

**Comment by saracope** [comment]
@jfredrickson5 -> https://waffle.io/saracope/open-gsa

**Comment by jfredrickson5** [comment]
I set up a board, we should figure out how best to use it.

https://waffle.io/GSA/cto-website
