### ISSUE TITLE
As a project manager of a closed source project, I would like a guide on transitioning from closed source to open source

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#134]
Refer to Source Code Policy from OMB as a foundation for doing this.

Then elaborate on specific steps:
* scrubbing private keys, passwords, etc, from source files
* ensuring private data doesn’t go public (publish code rather than data)
* be aware of information stored in source control history, and learn how to ensure old private data in the history is not released

**Comment by afeld** [comment]
Of interest: https://github.com/cfpb/open-source-project-template/blob/master/opensource-checklist.md

**Comment by jfredrickson5** [comment]
We'll want to adapt most of these checklist items, thanks @afeld!
