### ISSUE TITLE
As a PM or executive with no agile experience, I want a guide to understand agile, its benefits, and use cases in which it should be applied in clear terms so that I can decide whether I should implement it in my project/program

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#137]
Agile in simple terms

Use Case - What type of efforts does Agile make sense?

Time commitment from my staff to make it a success?

Think about executives (high level understanding, benefits, results)

Alternatively: Can we enhance existing guides? Are existing guides simple enough? Need to take a closer look.

**Comment by aliciacyrus** [comment]
Hi Jeff, this item has been created and published:
https://federalist.18f.gov/preview/GSA/cto-website/dev/guides/0_a_guide_newtoagile/

Please let me know if other information is required in order to close it.

**Comment by jfredrickson5** [comment]
Good stuff, thanks! 👍
