### ISSUE TITLE
As a GSA IT employee, I want to find guidance on agile contracting language so that I can provide requirements to produce effective agile contracts

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#138]

**Comment by aliciacyrus** [comment]
@Lulitts

**Comment by Lulitts** [comment]
@aliciacyrus, @jfredrickson5, I have developed a number of guidance articles on Agile contracting language that Navin is reviewing.

**Comment by jfredrickson5** [comment]
@Lulitts can we close this one with the addition of the PWS template, or is there more work yet to be done?
