### ISSUE TITLE
Improve H5/H6 accessibility

### ISSUE THREAD

**Issue by jcastle** [GSA/cto-website#15]
There is a concern for H5/H6 headings defined in main.scss not being compatible for accessibility. All other text should also be evaluated.

**Comment by jfredrickson5** [comment]
Although the text at H5/H6 meets the 4.5:1 contrast ratio test, it is still quite light at smaller sizes, so we need to look at using a darker color for H5/H6.

**Comment by jcastle** [comment]
I did this by commenting out the Headers in main.css which then makes the Headers default to USWDS standards.  This meets the contrast requirements.
