### ISSUE TITLE
Add the GSA IT logo

### ISSUE THREAD

**Issue by nvembar** [GSA/cto-website#150]
The GSA IT logo needs to be added to tech.gsa.gov!

**Comment by Lulitts** [comment]
http://gsa.github.io/open.gsa.gov.github.io/images/logo.jpg
Does this work?

**Comment by jcastle** [comment]
Need to have a png or photoshop file of a high res image with no background.  This will allow it to scale and not have a funny background when placing on various webpage backgrounds.  Attached GSADS logo as an example.  Might need to call in a favor with a graphic artist.

![gsa_wings_revised](https://cloud.githubusercontent.com/assets/5223678/23026121/461ec62e-f42e-11e6-936f-c9871bee21cf.png)

**Comment by nvembar** [comment]
Digging into it, we should have it.

**Comment by jfredrickson5** [comment]
I can convert the JPEG and do a bit of Photoshop to clean up the artifacts if needed.
