### ISSUE TITLE
Update the header to say "Tech at GSA"

### ISSUE THREAD

**Issue by nvembar** [GSA/cto-website#151]
Remove the language that makes this specific to the CTO's office.

**Comment by jfredrickson5** [comment]
Do you also want to make it a more general "Tech at GSA" theme as opposed to "CTO" throughout the site, not just the header? For instance, Guides are currently called "GSA CTO Guides", and could be updated to something like "GSA Tech Guides".

**Comment by nvembar** [comment]
Yup - I don't want the CTO's office totally erased given that we have a responsibility for setting technology strategy, for example; but at a guide level, I think this approach makes sense.
