### ISSUE TITLE
As a GSA executive, I want to see a link on the left menu of the Guides page so that I can easily access all guides relating to executive roles.

### ISSUE THREAD

**Issue by Lulitts** [GSA/cto-website#153]
**Acceptance Criteria**
Executive users will have: 
- A link labeled "Executives" on the left hand menu of the Guides page - Below All guides and above the "Developers" menu link
- Clicking the "Executives" Link will return list of guide titles that are specifically tagged for Executives during creation and publishing
- Users can navigate to specific pages of a guide by clicking on the hyperlink title from the list on the right

**Comment by jfredrickson5** [comment]
@Lulitts Since we decided to downsize to just categories and eliminate audiences, do you still have some interest in figuring out a category for execs, or should we close this issue?

**Comment by Lulitts** [comment]
@jfredrickson5, I think we can close this one at this point.
