### ISSUE TITLE
Adjust image size in Applying Agile Practices - Agile Legal

### ISSUE THREAD

**Issue by aliciacyrus** [GSA/cto-website#168]
Hello! Is there a way to make this 3/4 the size of a full image? The full size is too large, but this half-size seems a little...too small. :/

**Comment by jfredrickson5** [comment]
I'll add a new style that you can use to make 3/4 width images the same way you do half-size. Will let you know when it's in.

**Comment by jfredrickson5** [comment]
@aliciacyrus please try `guide-image-three-fourths` where you would normally use `guide-image-half`.

**Comment by aliciacyrus** [comment]
Thanks, Jeff!

Regards,

*Alicia J Cyrus*
General Services Administration
Phone: 202-549-9462
alicia.cyrus@gsa.gov

**Comment by aliciacyrus** [comment]
@jfredrickson5 It looks great! Thank you!
