### ISSUE TITLE
Modify Vision page to incorporate new Guide structure

### ISSUE THREAD

**Issue by jcastle** [GSA/cto-website#17]
@AliciaCyrus is making the content now and should have before Thursday meeting with Navin.  Just in case, this issue will keep it on the radar.

**Comment by jcastle** [comment]
Working on this tonight.  Want to turn this material into knowledge guide(s).  Will continue to work with @aliciacyrus to build out basic page until guides are built.

**Comment by jcastle** [comment]
Also have a branch open for this, cto_vision.

**Comment by jcastle** [comment]
Utilize new Guide structure.  Point each vision statement to a Guide with more information and documents.

**Comment by jfredrickson5** [comment]
I could add a "vision" metadata element to the guides. Then when you write a guide, you can optionally specify which vision elements it fits under. We could then have the vision page automatically pull in related guides for each vision element.

**Comment by jcastle** [comment]
This works.  @jfredrickson5 lets not overthink this just yet.  Want to get content built out.  Going to close this out and merge.  Will need to update the guide links to the proper guides once they are created.
