### ISSUE TITLE
Web Design Standards on Tech at GSA site

### ISSUE THREAD

**Issue by AndreaSigz** [GSA/cto-website#171]
Hi!

Per Navin's offer on Slack, here is some guidance in a Google Doc on the Web Design Standards to add to the Tech at State site. 

https://docs.google.com/document/d/1O1jZ2r8B7ffM0-sXjKjt0Sdcu_m7Dc3PqNsE1hlC_8I/edit#

Let me know if you have any questions.
Thanks!
Andrea

**Comment by jfredrickson5** [comment]
Thanks, [added to the site](https://tech.gsa.gov/guides/web_design_standards/)! Please feel free to suggest any future edits via issues or pull requests.

**Comment by AndreaSigz** [comment]
Awesome! Thanks so much @jfredrickson5
