### ISSUE TITLE
Streamline Agile Glossary & Remove DevOps Glossary

### ISSUE THREAD

**Issue by aliciacyrus** [GSA/cto-website#179]
Hi @jfredrickson5 , What's the easiest way to streamline the current Agile Glossary to just "Glossary"?
1) First, is there a way to identify any additional links to the current DevOps Glossary (I believe there is only one and I've updated it, but just to be sure)?
2) Is there a way to identify any links to the current Agile Glossary so that I can update them before changing the name of the file?

fyi: @Lulitts - I'm changing the name of the glossary file so it's not specific to any content type.

**Comment by jfredrickson5** [comment]
I don't believe there's an easy way to do it on the GitHub web interface. I do have tools that could handle the renaming and a global update of all the links. Let me know if you'd like me to do that:

* Rename "Agile Glossary" to "Glossary"
* Update all "Agile Glossary" links to "Glossary"
* Merge "DevOps Glossary" content into "Glossary"
* Update all "DevOps Glossary" links to "Glossary"

**Comment by aliciacyrus** [comment]
Hi @jfredrickson5  We don't need the third item _(Merge "DevOps Glossary" content into "Glossary")_ because I already updated the Agile Glossary content. 

The other steps - will take care of it! THANK YOU so much!

- Rename "Agile Glossary" to "Glossary"
- Update all "Agile Glossary" links to "Glossary"
- Update all "DevOps Glossary" links to "Glossary"

**Comment by jfredrickson5** [comment]
OK! It's in place on the dev preview; let me know if you have any issues.

**Comment by aliciacyrus** [comment]
Looks great, @jfredrickson5 & Thanks again! Should I go ahead and delete the DevOps Glossary?

**Comment by jfredrickson5** [comment]
Yes, go ahead, all the links have been updated so it's safe to delete.
