### ISSUE TITLE
Add content: User Stories guide

### ISSUE THREAD

**Issue by saracope** [GSA/cto-website#182]
Convert the 'Writing effective user stories' guide from a .pdf to markdown and post as a guide.
Reference: https://federalist-proxy.app.cloud.gov/preview/gsa/cto-website/dev/assets/downloads/UserStoryExamples.pdf

**Comment by aliciacyrus** [comment]
Thanks, Sara! I will also share the Google Doc with you, Kehinde, & Aamer! Please prioritize as needed, we have the .PDF up in the meantime.

**Comment by Ogunken** [comment]
I am working on this right now

**Comment by aliciacyrus** [comment]
Hello! Just checking in on the progress of this page.

**Comment by KehindeOgundolie** [comment]
Hey Alicia,

I have completed the writing the document and I am just waiting for Sara to approve it.

**Comment by aliciacyrus** [comment]
Awesome - thank you, Kehinde!

**Comment by saracope** [comment]
@aliciacyrus The document has been added in [dev](https://federalist-proxy.app.cloud.gov/preview/gsa/cto-website/dev/guides/user_story_example/), please have a look at the content. We will update the underscores showing in the title.

**Comment by KehindeOgundolie** [comment]
@aliciacyrus The title has been fixed.

**Comment by aliciacyrus** [comment]
It looks great (Go, @KehindeOgundolie !!!), just some minor tweaks. The acceptance criteria for each user story should just be in one table block with a bulleted list, for example:

Ensure the Acquisition Gateway User is able to:
- log in to Acquisition Gateway
- navigate to the Auction page
- able to select a product(s) to bid on

If the dashes are creating the extra table sections, then just use regular bullets.

**Comment by KehindeOgundolie** [comment]
@saracope I have made edits to the table. Thanks

**Comment by saracope** [comment]
This one is in production. Good to close? @KehindeOgundolie @aliciacyrus

**Comment by aliciacyrus** [comment]
Looks great to me @saracope ! Thank you, @KehindeOgundolie !

**Comment by saracope** [comment]
Great! Closing out.
