### ISSUE TITLE
Add content: Measures of Success in an Agile Organization

### ISSUE THREAD

**Issue by saracope** [GSA/cto-website#183]
Add guide for Measures of Success in an Agile Organization sent by Lulit.

**Comment by Aamer21** [comment]
I am working on it

**Comment by Lulitts** [comment]
@Aamer21, do you have a timeline when this will be published?

**Comment by saracope** [comment]
@Lulitts He is done with this one. I will push it to a branch and drop a link here in a few for you to review.

**Comment by saracope** [comment]
@Lulitts https://federalist-proxy.app.cloud.gov/preview/gsa/cto-website/sc_measuring-agile-success/guides/measuring-agile-success/

**Comment by Lulitts** [comment]
Thanks @saracope & @Aamer21!

**Comment by Lulitts** [comment]
@saracope, I noticed some content cuts off in the second table - Metrics column, second row - 
Here is the source document:
https://docs.google.com/document/d/1UG4V37e94vG3Am7EJBjE-NtkBt7xmwkzUS-e-54kpWM/edit#heading=h.1m9v4e4wxgi2
Can I commit this change in dev before you push it?

**Comment by saracope** [comment]
You can make changes on this branch: https://github.com/GSA/cto-website/tree/sc_measuring-agile-success

**Comment by saracope** [comment]
I just updated this in production. Can you have a look? @Lulitts

**Comment by Lulitts** [comment]
Thanks @saracope! Looks great now. Would it be possible to add the "Tips" bullets into a table-box?
