### ISSUE TITLE
Add content: Devsecops guide

### ISSUE THREAD

**Issue by saracope** [GSA/cto-website#184]
Add Standard DevSecOps Platform Framework from Jeff.

**Comment by Ogunken** [comment]
I am going to work in this issue

**Comment by Aamer21** [comment]
My work in this issue

**Comment by saracope** [comment]
@Aamer21 Finish adding text with proper Markdown formatting.

**Comment by saracope** [comment]
@jfredrickson5 This guide has been added, closing issue.
