### ISSUE TITLE
Please Publish Site

### ISSUE THREAD

**Issue by aliciacyrus** [GSA/cto-website#195]
Hi @jfredrickson5 @saracope , whenever you get a chance, will you please publish the site? I made some changes to the "Guide: New to Agile?" page that need to go live. Thanks so much!

**Comment by saracope** [comment]
Will do.

**Comment by saracope** [comment]
I pushed the changes and the build has completed. Please have a look.

**Comment by aliciacyrus** [comment]
Looks great, thanks @saracope ! :)

**Comment by saracope** [comment]
👌
