### ISSUE TITLE
Create the five pillars of the CTO vision

### ISSUE THREAD

**Issue by jcastle** [GSA/cto-website#2]
Fill in the remaining text that speak to the five pillars

- [x] Consider including the presentation in an HTML format
- [x] Determine best layout and CSS
- [x] Consider changing title link to "Vision"

**Comment by nvembar** [comment]
I would also add: make sure that the brief descriptions of the vision elements are easily discoverable, if not immediately on the page. 

We want to use the vision to drive people to content and then also drive a task-oriented structure to content as well ("I want to convert my team to Agile, what do I need to do?")

**Comment by jcastle** [comment]
Going to add files for supporting materials later - will create a separate issue.  Need to add role-based features or questions.

**Comment by jcastle** [comment]
Creating a new issue for the role-based materials.  This issue is closed as the Vision page is up and running.
