### ISSUE TITLE
grouping of Guides

### ISSUE THREAD

**Issue by afeld** [GSA/cto-website#208]
I wanted to send information about GSA's DevSecOps work around, and noticed that there are a few Guides related to it under https://tech.gsa.gov/guides/, but they don't seem to be cross-linked or in a group I can link to. Therefore, I'm just telling people to "search 'DevSecOps'" on the list of Guides. Would love to have a linkable entry point, whether that's one of the Guides that links out to the others, or somewhere else that lists them. Thanks!

**Comment by afeld** [comment]
Another option: list it as one of the Projects, and put all the links there.

**Comment by saracope** [comment]
We have a DevOps category to help folks filter down to just those documents. Will that work? Are these all these ones you're referring people to?  

![screen shot 2017-08-23 at 10 08 31 am](https://user-images.githubusercontent.com/2197515/29620175-38dd5ef2-87eb-11e7-998e-236d8757ed74.png)

**Comment by afeld** [comment]
Yeah, I saw - I guess being able to link to that Category would suffice. This issue may actually be more about needing a good entrypoint for the DevSecOps work than about the grouping.

**Comment by saracope** [comment]
Yeah, that def. makes sense and could be useful for all the categories.

**Comment by jfredrickson5** [comment]
I've had improved entrypoints in mind for a while now but it's taken a back seat to other work lately.

I was thinking of implementing something via URL fragments, updating the browser's location every time you select a set of categories. Sharing a specific category or set of categories would then be just a matter of sharing the current URL.

**Comment by jfredrickson5** [comment]
@afeld could you please review?

https://federalist-proxy.app.cloud.gov/preview/gsa/cto-website/linkable-guide-categories/guides/

It updates the URL as you change filter options, so once you've set the filters the way you want them, you can share the URL.
