### ISSUE TITLE
Add first/last name metadata to Team collection

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#21]
We should be able to sort team members by last name, so we need a bit more metadata in the team member files to accomplish that.

**Comment by jcastle** [comment]
Can more instructions be added to the team.md file to let people know how/where to write out their full bio and attach docs (pdf version, resumes, design work, projects, etc.)?

**Comment by jcastle** [comment]
Also, space out the visual display of the page to account for longer titles.  Mine looks choppy and others might be longer.
