### ISSUE TITLE
Push Live

### ISSUE THREAD

**Issue by aliciacyrus** [GSA/cto-website#214]
Hi @jfredrickson5 , can we go ahead and push live

**- conducting_sprint_review_session.md**

Also, in the file is a link to a the template, **SampleSprintReviewPresentation.pptx**, which I uploaded in the Assets>>Downloads folder. Is this linked correctly? Thank you!

**Comment by jfredrickson5** [comment]
Yes, the link should be correct on the live site. I'll get this out now.
