### ISSUE TITLE
Vision page needs a way for users to contact us

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#22]
There is a "Contact Us" link in the footer on each page; this may suffice. But we can also look at ways visitors may want to contact us while they are on the Vision page.

**Comment by jcastle** [comment]
I think on this, within each accordion we offer responses to the questions, links, etc.  And then say if you still want more information to contact us.

**Comment by jcastle** [comment]
Not relevant after creating guides and Contact Us in the Footer.
