### ISSUE TITLE
Push Live :)

### ISSUE THREAD

**Issue by aliciacyrus** [GSA/cto-website#221]
Hi @jfredrickson5 @saracope , I updated the Case Studies and made some minor edits to Conducting a Sprint Review. Will you push those live when you get a chance? Thank you!

**Comment by aliciacyrus** [comment]
Hi @jfredrickson5 @saracope , Just following up. Thank you!

**Comment by saracope** [comment]
@aliciacyrus  Do you have an hour tomorrow to go through this? I'd like to change your workflow a bit so it's easier to manage.

**Comment by aliciacyrus** [comment]
@saracope Yes, I do! Just send me an invite.

**Comment by aliciacyrus** [comment]
@saracope Let me know if you have time to revisit this. BTW, do you mind pushing "Conducting a Backlog Refinement (Grooming)" live? ;) Thank you!

**Comment by saracope** [comment]
@jfredrickson5 Can you look at this? I am ooo.

**Comment by jfredrickson5** [comment]
Doing this now. Also, we are going to change that GitHub workflow.
