### ISSUE TITLE
Graphic elements for Vision page

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#23]
Add graphics to the Vision page. Each of the five pillars should be associated with an icon/illustration that represents its theme. Could be a simple icon, or could be more elaborate illustrations. The look of each graphic should be consistent with graphics throughout the site.

**Comment by jfredrickson5** [comment]
We really could use a graphic designer right about now. :)

**Comment by jcastle** [comment]
@nvembar support from 18F would be nice here, the 40hrs for a graphic designer for this and open.gsa.  Will continue working, in the meantime, we will look for free stuff.
