### ISSUE TITLE
remove deploy step

### ISSUE THREAD

**Issue by afeld** [GSA/cto-website#234]
Just curious: is there a benefit to not having the primary branch be the canonical thing deployed to Federalist? I've been watching this repository for a while and see issues like #195 #211 #214 #221 come up, and wonder if having the extra deploy step is actually adding any value. Continuous deployment has worked well for other Federalist sites.

**Comment by jfredrickson5** [comment]
The process was initially to provide a preview area for various changes at once, but it may be better to just merge into master/production from feature branches, since we do have the preview capability in PRs, and feature branches can be merged into each other if necessary.

**Comment by aliciacyrus** [comment]
Sorry, I was re-reading this, didn't mean to close it!

**Comment by jfredrickson5** [comment]
Eliminated `dev` branch from the workflow. Updated the README and related wiki pages to indicate that feature branches and PRs should be used.
