### ISSUE TITLE
no way to navigate to the tech talks?

### ISSUE THREAD

**Issue by afeld** [GSA/cto-website#254]
I saw the pull request to add my talk to the site (#253), but clicking through the site, couldn't figure out where it appears. Ended up Googling it 😛

https://tech.gsa.gov/techtalks/

Might want to link to that page from the navigation or something.

**Comment by jfredrickson5** [comment]
We have a redesign in the works that'll make the Tech Talks section more prominent in the nav menu.

**Comment by jfredrickson5** [comment]
Added Library section in PR #341 to link to all learning resources such as Tech Talks.
