### ISSUE TITLE
Define project stages

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#27]
For the projects page, we will have projects listed. Each project will be in a stage. We need a page that defines what each stage means.

**Comment by saracope** [comment]
Will these match up with the stages we have in Jira?

**Comment by jfredrickson5** [comment]
They could, but we need to come up with a solid definition of what we consider to be our formal project stages. We'll have to have a conversation on that. We can't resolve this issue until we decide on our project methodology.

**Comment by jfredrickson5** [comment]
This is gonna have to go into the backlog until we finalize our project intake process.
