### ISSUE TITLE
Fix link

### ISSUE THREAD

**Issue by saracope** [GSA/cto-website#288]
From a feedback form submission:

"Links not correct in Agile Projects Page (https://tech.gsa.gov/guides/conducting_an_agile_project/)
Please correct the link for Agile Sprint Retrospective"

It looks like the Retrospective link to pointing to the Spring Demo page. It should point to: https://tech.gsa.gov/guides/conducting_sprint_retrospective/

**Comment by saracope** [comment]
@KehindeOgundolie Interested in making this change?

**Comment by KehindeOgundolie** [comment]
@saracope Working on this right now

**Comment by jfredrickson5** [comment]
Done, thanks @KehindeOgundolie and @saracope!
