### ISSUE TITLE
Create a training page

### ISSUE THREAD

**Issue by saracope** [GSA/cto-website#300]
Create a training page to include the TechTalks and Data Science info we're working on. Here's what I'm thinking - 

1. Add Training link to the top menu:
<img width="662" alt="screen shot 2018-06-06 at 11 15 05 am" src="https://user-images.githubusercontent.com/2197515/41047647-0738e520-697b-11e8-928b-46deff30d810.png">

2. Create Training page that include widget for both TechTalks and DS (this is a rough prototype)
<img width="1321" alt="screen shot 2018-06-06 at 11 16 34 am" src="https://user-images.githubusercontent.com/2197515/41047700-27250508-697b-11e8-97fa-a9083f34acc5.png">

Thoughts @jfredrickson5

**Comment by jfredrickson5** [comment]
This is good! Putting Tech Talks in a more prominent location has been on the back burner for too long, and I don't think we even have any mention of Data Science at all yet.

**Comment by saracope** [comment]
Awesome. I'm going to go ahead and work with @KehindeOgundolie to have her start the changes.
