### ISSUE TITLE
Site is hosted over https but resources are being requested over http

### ISSUE THREAD

**Issue by rmcc13** [GSA/cto-website#36]
Hi, I just visited the site and noticed that stylesheets and scripts were not loading. The site is hosted over https but the resources are being requested via http. I believe the cause of this is the url property in your _config.yml is using http.

**Comment by jfredrickson5** [comment]
Thank you for the report! GitHub's Jekyll site.github.url doesn't seem to factor in HTTPS enforcement. Switching to site.baseurl for now.
