### ISSUE TITLE
Consider search - look at Digital Gov for search support

### ISSUE THREAD

**Issue by jcastle-zz** [GSA/cto-website#4]
Consider incorporating search on site via Digital Gov - http://search.digitalgov.gov

**Comment by jcastle** [comment]
We can research in Sprint 2 and see what happens.  Might have to wait until we get to Federalist.18f.gov.

**Comment by jfredrickson5** [comment]
Leaving this in the backlog for now because we need a more clear picture of where we're heading with content and design before determining how to implement search.

**Comment by afeld** [comment]
Another option: https://github.com/18F/jekyll_pages_api_search

**Comment by jfredrickson5** [comment]
@afeld thank you, the Jekyll search plugin looks very promising for our needs. Now that we are using Federalist, we can use custom plugins.
