### ISSUE TITLE
GSA Tech Guides: Design guides - USWDS name and link updates

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/cto-website#430]
On the [Web Design Standards](https://tech.gsa.gov/guides/web_design_standards/) page, 

 - [ ] the name needs to updated from `Web Design Standards` to `U.S. Web Design System`

**A: Current copy links to old URL, https://standards.usa.gov/:** 

> Web Design Standards 
> 
> What are the Web Design Standards? 
> 
> The [Web Design Standards](https://standards.usa.gov/) is a library of design guidelines and code to help government developers and designers quickly create trustworthy, accessible, and consistent digital government services.

Correction includes new website link, https://designsystem.digital.gov: 

> U.S. Web Design System 
> 
> What is the U.S. Web Design System? 
> 
> The [U.S. Web Design System](https://designsystem.digital.gov) (USWDS)&mdash;formally known as the U.S. Web Design Standards&mdash;is a library of design guidelines and code to help government developers and designers quickly create trustworthy, accessible, and consistent digital government services.

**B: Other corrections needed on this page:** 

> The Standards allow designers and developers ...

USWDS allows designers and developers ...

> The Standards offer code and guidelines for ...

USWDS offers code and guidelines for ...

> Our team is also available to work closely with you to develop custom features or train teams on implementing the Standards.

... or train teams on implementing the System.

> This project is maintained by 18F, an office within GSA.

This project is maintained by the [Office of Products and Programs](https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services/office-of-products-and-programs), an office within the [Technology Transformation Services](http://www.gsa.gov/tts) (TTS) at GSA.

***
**_Note_**: For now, will leave "Thus the Standards was born." at the end of the 2nd paragraph as is b/c it began as Standards, and will defer to Dan Williams on how/if this needs an edit.

**Comment by jfredrickson5** [comment]
Thanks @ToniBonittoGSA! I've made the updates. I also went ahead and updated the GitHub links and the contact email address as well. Let me know if there are any additional changes you need.
