### ISSUE TITLE
Guide - Onboarding

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#46]
New CTO employees need to know some things in addition to what they learned during orientation:
- Requesting access to systems
- Travel
- HR paperwork
- IT equipment requests
- Other items?

**Comment by jcastle** [comment]
@CinnyaSm, work on process guides in Google Docs and I can port them over to the website.  Maybe you can learn Markdown and do them on your own in the future.

**Comment by saracope** [comment]
Submitted pr (#63) for this.
