### ISSUE TITLE
Complete Work With Us page

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#50]
This page should contain an introduction to the specific services CTO offers. The page should contain a project intake form (or have a prominent link to a project intake form). The goal of this page is to let our potential customers sign up to do projects with us.

**Comment by jcastle** [comment]
Automate with JIRA, move the data from the form to a queue.

**Comment by saracope** [comment]
Just do the form initially, then expand the content.

**Comment by jcastle** [comment]
For the form, we should use the Agile investment document.  If you want to setup the form, I can add the text.  Add something generic to start.

**Comment by jcastle** [comment]
Text looks good.  Make sure to incorporate with Sara's form.
