### ISSUE TITLE
Complete Project page

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#51]
This page serves as a project dashboard. It lists all our projects. For each project, we should have a brief description, a link to the app if applicable, a link to the GitHub repo, and the status of the project according to our formal project stages (if any).

Can be static Markdown/HTML page for now but ideally will pull data from a project API server in the future.

**Comment by jcastle** [comment]
Potential projects: NSA, PBS, cto.gsa.gov, open.gsa.gov, openopps, OCSIT (TTS, Sara), open source policy implementation

**Comment by saracope** [comment]
I'll work on summarizing our projects for this.

**Comment by saracope** [comment]
Added the [projects](https://github.com/GSA/cto-website/tree/projects) branch for this change. Can you review @jcastle?
