### ISSUE TITLE
Guide framework/structure

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#52]
Restructure the Guides section so that guides are divided into categories. Those categories can be based on role. Example: https://www.gov.uk/service-manual

**Comment by jfredrickson5** [comment]
I'm thinking that each guide can have "category" and "audience" metadata fields. Each guide can have multiple audience types. I also think that initially each guide should only fit into one category, though it'd certainly be possible to assign a guide to multiple categories.

This will allow us to primarily organize the guides into categories, while also allowing us to highlight useful guides for specific audiences.

Possible categories, along with example guide topics:

- Agile
  - Introduction to the idea of agile
  - How you know you're doing agile well
  - How to do Scrum
  - How to do Kanban
- UI/UX/Accessibility
  - User-centered design
  - Accessibility/508
  - Data visualization
  - Plain language
- Governance
  - Open source
  - Open data
  - Enterprise adoption of agile principles
  - Policy implementation
  - IT organizational structure (e.g., DevOps vs traditional)
- Development
  - Coding practices
  - Source control practices
  - API guidelines
  - Testing practices
  - Release engineering
  - DevOps

Possible audiences:

- Developers
- Executives
- Project managers
- UI/graphic designers
- Operations
- Information security
- Non-technical stakeholders
- Content editors

**Comment by jcastle** [comment]
The structure looks good.  I would stay away from "governance" as it connotes something legacy.  We can come up with a different name.

For now, we can have placeholder links for all of the categories and roles and then work to build them out.

**Comment by afeld** [comment]
The information architecture is far from perfect, but here is @18F's list:

https://pages.18f.gov/guides/
