### ISSUE TITLE
Enhance graphic elements

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#53]
Identify which information or design elements would be enhanced by having accompanying graphics (pictures, diagrams, icons, etc). There are some parts of the site that are text-heavy and may benefit from graphics.

This issue will be used to line up some work for graphic design.

Checklist:
- [ ] [CTO Vision](http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/GSA/cto-website/vision/) icons: Each of the five vision elements has its own icon (currently from Font Awesome). We would like icons that better match each vision element. These icons would be reused wherever we have the vision elements, such as on the front page.
- [ ] [Front page](http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/GSA/cto-website/) hero image: This is currently a photo of the White House and some sky, but it would be nice if it were more relevant to GSA. It can be a photo or an illustration.
- [ ] [Project Stages](http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/GSA/cto-website/): Diagram illustrating the process of moving from Discovery to Alpha to Beta to Live (might be the same as Work With Us diagram, above). Also, an icon to represent each stage (Discovery/Alpha/Beta/Live).
- [ ] [Work With Us](http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/GSA/cto-website/work-with-us/) page: Diagram illustrating the process of moving from pilot to prototype to scaled finished product (might be the same as Project Stages, below).
- [ ] [About Us](http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/GSA/cto-website/about/) page: Visual elements for each of the sections that correspond with the items listed in Mission, Responsibilities, and Goals.

All of the illustrations or photos provided must have no copyright or usage restrictions.

**Comment by jcastle** [comment]
Graphic designer on the way.  @jfredrickson5 you might want to make a list of items for the designer to work on.  She will only be around for 40hrs total.  We can get more if needed but this will be the start.

**Comment by mtorres253** [comment]
Hi @jfredrickson5 and @jcastle this looks great. The links to the pages aren't working though. Possible to fix before our meeting on Thursday?

**Comment by jfredrickson5** [comment]
@mtorres253 fixed!

**Comment by mtorres253** [comment]
@jfredrickson5 Also have a suggestion from our design team that we specify that we are looking for them to provide a suitable photograph for the hero image with no copyright or usage restrictions.

**Comment by jfredrickson5** [comment]
@mtorres253 should that requirement apply to all the design work we are receiving or are photos different than illustrations?

**Comment by mtorres253** [comment]
@jfrederickson5 Good question. I'm asking and will post when I have an answer

**Comment by mtorres253** [comment]
@jfredrickson5 yes, it applies to all images and illustrations used.

**Comment by jfredrickson5** [comment]
@mtorres253 Updated the checklist to specify that all the images we get should have no usage restrictions. Also specified that the hero image can be a photo or illustration because we don't have anything specific in mind but just want it to be relevant to GSA and CTO.
