### ISSUE TITLE
Add team information

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#6]
Set up a Jekyll data file with team member info, pull that into the team page

**Comment by jcastle** [comment]
Similar to 18F format with circle pics.  Click on pic for another page with short bio.  Allow for pdf bio doc for speaking engagements (this will drive traffic to cto.gsa.gov).

**Comment by jfredrickson5** [comment]
I've added the team bio framework. Just need everyone to submit their info now.

https://github.com/GSA/cto-website/wiki/Add-your-profile-to-the-Team-page

**Comment by jcastle** [comment]
Have the look and feel of 18F people page, https://18f.gsa.gov/team/.
