### ISSUE TITLE
Develop front page content

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#7]
Need content for the front page: http://cto.gsa.gov/

- [x] consider additional content for the home page - look at 18F

**Comment by jfredrickson5** [comment]
We should separate issues into individually addressable units, rather than combining many changes into one issue. Another reason to separate out unrelated work into multiple issues is because, when doing a Git commit that mentions an issue, it will automatically close the issue. It's best to have small commits that each fix a specific issue, not a massive commit that fixes many things.

I am going to move footer refactoring into a separate issue.

BTW, the only reason the footer navigation links are in the middle of the screen is because there is no front page content yet. Adding content will automatically push those links down to the bottom.

**Comment by jcastle** [comment]
This thing looks awesome.  Going to close this issue and merge my code with the master (gh-pages).
