### ISSUE TITLE
Add progress measure to Projects page

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#72]
We need a progress indicator for each project listed on the Projects page. This will identify which stage each project is in.

**Comment by jcastle** [comment]
Design similar to 18F project dashboard.

**Comment by jfredrickson5** [comment]
@jcastle and @saracope Everything should be in place now, but can you update any respective projects you may have by adding a line for Stage and a line for Repository? Specifically, Federal Innovation Toolkit and NSA. You can use the entry for cto.gsa.gov or open.gsa.gov as an example.

**Comment by jcastle** [comment]
@jfredrickson5 I get an error message when I click on "Alpha."  Also, can you separate the projects with an <hr> or something to help the eye distinguish between them?

**Comment by jfredrickson5** [comment]
@jcastle have you pulled the latest from master? It should have a new Project Stages page. Alpha, etc link to there.

**Comment by jcastle** [comment]
A little out of scope, but adding small screen captures might be cool too.  Something like, https://www.usds.gov/work.

**Comment by jcastle** [comment]
@jfredrickson5 looking at the preview site, have you not merged yet?

**Comment by jfredrickson5** [comment]
@jcastle Ahh, needed the baseurl. Link should work on the preview site now. Also added the horizontal rules.
