### ISSUE TITLE
Guide - Open Databases

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#74]
From @nvembar, see Edward's document regarding transitioning to open source databases.

**Comment by nvembar** [comment]
I'd like to delete that document for the moment.

**Comment by jcastle** [comment]
The doc is off the site but still in the folder.  Do you want us to take out of the folder too?

**Comment by nvembar** [comment]
Yes, thank you!

**Comment by jcastle** [comment]
Removed the doc from the repo.

**Comment by jfredrickson5** [comment]
Do we want this eventually added to the guides or are we dropping it?
