### ISSUE TITLE
Set up cto.gsa.gov hostname

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#77]
Need to submit a DNS change request and see if we need to coordinate with Federalist/18F to configure a custom hostname.

**Comment by jfredrickson5** [comment]
Existing cto.gsa.gov is a CNAME pointing to GitHub Pages. Once everything is set up with Federalist, we just need to put in a request with GSA IT to update that.

**Comment by IanLee1521** [comment]
Once it's up, can you also add it to the GitHub repository metadata?

**Comment by jfredrickson5** [comment]
Changing to tech.gsa.gov rather than cto.gsa.gov.
