### ISSUE TITLE
Remove digital.gov API

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/cto-website#880]
It looks like the [digital.gov API](https://open.gsa.gov/api/digitalgov/) mostly works, but there are four endpoints with 404s:
- Blog Posts JSON - Single Community - All Tags - All Categories

4/18:
Hi Vicki,

I didn't even know we had an API. This must be some legacy endpoints. We plan to migrate to a new content management system soon. Instead of fixing our API, I recommend removing the listing from [open.gsa.gov](http://open.gsa.gov/). Is that possible?

Ammie

**Comment by jfredrickson** [comment]
PR: https://github.com/GSA/open-gsa-redesign/pull/1203

Preview here: https://federalist-ecc58765-2903-48b3-920c-5d93318ad084.sites.pages.cloud.gov/preview/gsa/open-gsa-redesign/jf/remove-digital-gov-api/api/
