### ISSUE TITLE
Decomission tech talks that are 2+ years old

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/cto-website#888]
- [ ] Remove tech talks that are 2+ years old
- [ ] archive the previous talks and PDFs in a way that they don't build to the website but are still available in a repo

**Comment by jfredrickson** [comment]
Preview: https://federalist-cfade689-2192-403e-a4d0-0335f68f0203.sites.pages.cloud.gov/preview/gsa/cto-website/jf/filter-tech-talks/techtalks/

**Comment by vickimcfadden** [comment]
@jfredrickson looks good to me!
