### ISSUE TITLE
TechRadar changes

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/cto-website#889]
- Rename header to "emergent technology"
- Get rid of 'events', 'engagement', and 'about'
- Andrew P and Joe deR are going to refresh the rest of the content (card to come later)

**Comment by jfredrickson** [comment]
What do you want to do with the [main TechRadar landing page](https://tech.gsa.gov/techradar/)? The content has a couple of references to "TechRadar". We could update the content on the page, or we could remove it entirely and link directly to the [Emerging Technology page](https://tech.gsa.gov/techradar/technologies/) instead.

**Comment by vickimcfadden** [comment]
Delete and link under Emerging Technology page!

**Comment by jfredrickson** [comment]
@vickimcfadden [preview link](https://federalist-cfade689-2192-403e-a4d0-0335f68f0203.sites.pages.cloud.gov/preview/gsa/cto-website/jf/techradar-cleanup/)

PR: #911

**Comment by vickimcfadden** [comment]
@jfredrickson looks great, thank you!!
