### ISSUE TITLE
Tech stack pros / cons & documentation

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/cto-website#897]
- [x] develop pros & cons doc

**Comment by vickimcfadden** [comment]
@jfredrickson since you grabbed it, happy to let you run with this! Tag me how I can help (which should not be very much tbh, lol)

**Comment by jfredrickson** [comment]
@vickimcfadden couple of questions!

* Will the editors of the website continue to be the same CTO/SD folks that currently edit it?
* Will we fold in open.gsa.gov and continue to host API documentation for those who need a place to publish theirs?

**Comment by vickimcfadden** [comment]
@jfredrickson yes to both!

**Comment by jfredrickson** [comment]
Here's the [pros/cons document](https://docs.google.com/document/d/1CsmrNyH_0aAnmqaRnriLjRT_EwIraJ5o9wFbxZw4kIc/edit)!

**Comment by jfredrickson** [comment]
@brentryanjohnson I'd love for you to take a look at the [pros/cons](https://docs.google.com/document/d/1CsmrNyH_0aAnmqaRnriLjRT_EwIraJ5o9wFbxZw4kIc/edit) and see if there are any inputs to the tech stack from a content maintenance perspective.

**Comment by vickimcfadden** [comment]
thanks @jfredrickson – this doc looks great! I don't have opinions, so I defer to you all here.
