### ISSUE TITLE
Redesign the footer

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#9]
- [x] Footer links should go adjacent to the GSA DS logo.
- [x] consider making GSA DS logo smaller
- [x] consider taking the GSA DS wording out of the logo or the "built by GSA DS"

**Comment by jcastle** [comment]
@jfredrickson5 we should consider embedding the design standards CSS and JS files into our site.  We may not use all of the content in the files, but would help when we do invoke a style or function.  Also, with the footer, there are specific layouts already built, maybe use one of them.

**Comment by jcastle** [comment]
@jfredrickson5 you were one step ahead of me on this with including the uswds folder to the source files.  Good to go now for my pages and you can use for your footer etc.

**Comment by jcastle** [comment]
@jfredrickson5 consider making the GSA DS logo smaller and changing the wording either under the logo or above it so it doesn't say GSA DS in two places.

**Comment by jcastle** [comment]
Closing this one in lieu of Issue #7 Develop front page content.

**Comment by jfredrickson5** [comment]
The footer is not related to front page content; they should be separate issues. Front page content is only on the front page. The footer affects all pages.
