### ISSUE TITLE
Update API CISS on API standards repo

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/cto-website#916]
Currently we do not have access to this repo. 

- [x] Get access for Jeff, Wei, Mark, Ryan, Kristen, and Vicki

On the [GitHub API standards page](https://github.com/GSA/api-standards?tab=readme-ov-file) please change the text to say:

Add Your API To The GSA API Directory
(Public APIs) A directory of GSA public APIs is available at [open.gsa.gov/api](https://open.gsa.gov/api/). Add your API to this directory by posting an issue or pull request in the [GitHub repository](https://github.com/GSA/open-gsa-redesign).

Part of this process is to first complete the neccessary steps to add your GitHub Account to the GSA Organization and then send an email to the **CTO team** to have your account added to the open-gsa-redesign User Group. The steps are documented on the [Adding API Documentation](https://github.com/GSA/open-gsa-redesign/blob/master/APIDOCS.md) GitHub page.

**Comment by vickimcfadden** [comment]
@jfredrickson do you have access now?

**Comment by jfredrickson** [comment]
@vickimcfadden Yes, thanks!
