### ISSUE TITLE
Add back the DevOps guides

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/cto-website#969]
Add back the following guides:

- [Building a DevOps culture](https://federalist-cfade689-2192-403e-a4d0-0335f68f0203.sites.pages.cloud.gov/preview/gsa/cto-website/jf/service-desk-update/guides/building_devsecops_culture/)
- [DevSecOps guide](https://federalist-cfade689-2192-403e-a4d0-0335f68f0203.sites.pages.cloud.gov/preview/gsa/cto-website/jf/service-desk-update/guides/dev_sec_ops_guide/)
- [Understanding the difference btw Agile and DevOps](https://federalist-cfade689-2192-403e-a4d0-0335f68f0203.sites.pages.cloud.gov/preview/gsa/cto-website/jf/service-desk-update/guides/understanding_differences_agile_devsecops/)
- [What is DevOps](https://federalist-cfade689-2192-403e-a4d0-0335f68f0203.sites.pages.cloud.gov/preview/gsa/cto-website/jf/service-desk-update/guides/what_is_devops/)

**Comment by jfredrickson** [comment]
[Preview link](https://federalist-cfade689-2192-403e-a4d0-0335f68f0203.sites.pages.cloud.gov/preview/gsa/cto-website/jf/devsecops-guides/guides/)
