### ISSUE TITLE
Remove 3D printing article

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/cto-website#972]
The [3D printing article](https://tech.gsa.gov/techradar/3d-printing/) has some serious issues, remove it from the site.

**Comment by jfredrickson** [comment]
[Preview link](https://federalist-cfade689-2192-403e-a4d0-0335f68f0203.sites.pages.cloud.gov/preview/gsa/cto-website/jf/remove-3d-printing/techradar/)

**Comment by vickimcfadden** [comment]
LGTM Jeff!
