### ISSUE TITLE
add uswds identifier in footer for open.gsa.gov

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/cto-website#986]
Let's use the same footer as tech.gsa.gov except:

- tech.gsa.gov / Office of the CTO = open.gsa.gov / GSA Office of Office of Enterprise Data & Privacy Management
- Add a `contact us` link that links to https://open.gsa.gov/contact/

On the [contact us](https://open.gsa.gov/contact/) page, could we update the text from:
- the `GSA Office of the CTO` to `GSA Office of Office of Enterprise Data & Privacy Management` – the email (open@gsa.gov) is correct.

**Comment by jfredrickson** [comment]
@vickimcfadden 

[PR link](https://github.com/GSA/open-gsa-redesign/pull/1292) for review

[Preview link](https://federalist-ecc58765-2903-48b3-920c-5d93318ad084.sites.pages.cloud.gov/preview/gsa/open-gsa-redesign/jf/identifier/)

**Comment by vickimcfadden** [comment]
Thanks @jfredrickson - moving to done!
